### ISSUE TITLE
[P2PMoney] Remove airtable rows automatically on submission when the code isn't found in the Intake base 

### ISSUE THREAD

**Issue by mjmaurer** [crownheightsaid/mutual-aid-app#107]
https://crownheightsmutualaid.slack.com/archives/C010AUQ6DFD/p1593712985422600

**Comment by wrudebusch** [comment]
@mjmaurer 

Could we have a look-ahead / drop down and not allow non-valid codes to begin with? is this possible?

Which tables/columns should I be looking at?

**Comment by sandfort** [comment]
Since payment requests and delivery requests are in different bases, I don't think we could make either a drop-down or a validation in the form. Seems like linking between bases isn't supported: https://support.airtable.com/hc/en-us/articles/223299927-Can-I-link-between-different-Bases-

So, I think we would have to rely on something in our own app to look up if the request code matches up. However, I think it might be confusing for a payment request to simply not show up... if the request doesn't match, should we have the bot post an error message in the reimbursement channel? Or, if the requestor's Slack name is available, PM them?

**Comment by mjmaurer** [comment]
> So, I think we would have to rely on something in our own app to look up if the request code matches up. However, I think it might be confusing for a payment request to simply not show up... if the request doesn't match, should we have the bot post an error message in the reimbursement channel? Or, if the requestor's Slack name is available, PM them?

I should have added more context here! We [currently detect](https://github.com/crownheightsaid/mutual-aid-app/blob/master/src/workers/airtable-sync/actions/payments/newPaymentRequest.js#L201) if a request doesnt exist and will post a notification in slack to that effect. 

This issue is just adding a PaymentRequest row deletion to the codeNotFound logic.
